### ISSUE TITLE
Dynamic collection name based on date "YYYY-MM-DD"

### ISSUE THREAD

**Issue by rtcimi** [arvindr21/diskDB#16]
Hi, i love using your library for my projects it is simply awesome and everything always works like it should. Now i got a project where it would be realy ql if i could load/save collection named dynamicly by date... i've done some testing. Loading collection works ... but i'm having trouble/error when trying to save it ...  any idea?

**Loading (it is working):**
_var currentDateFileName = moment().format('YYYY-MM-DD');
... dbconn.connect('/', ['stuff', currentDateFileName ]);_

**Saveing (not working):**
_var saveToFile = conn.currentDateFileName.save(logRecord);_ 

/test5.js:214
var saveToFile = conn.currentDateFileName.save(logRecord);
                                                                      ^
TypeError: Cannot read property 'save' of undefined
    at logRegs (/home/pi/ctc2/test5.js:212:37)
    at Transaction.<anonymous> (/home/pi/ctc2/test5.js:183:6)
    at emitOne (events.js:77:13)
    at Transaction.emit (events.js:169:7)
    at /home/pi/node_modules/h5.modbus/lib/Transaction.js:320:19
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by rtcimi** [comment]
Sorry, stupid question ...
